import { test, expect } from '@playwright/test';

test('Filtrar por disciplina', async ({ page }) => {
  await page.goto('https://elrunix12.github.io/balanceterno/');
  await page.getByRole('checkbox', { name: 'Auditoria Contábil (19)' }).check();
  await page.getByText('Exibindo 19 questões.').click();
  await page.getByRole('checkbox', { name: 'Auditoria Contábil (19)' }).uncheck();
  await page.getByRole('checkbox', { name: 'Contabilidade Aplicada ao' }).check();
  await page.getByText('Exibindo 28 questões.').click();
  await page.getByRole('checkbox', { name: 'Contabilidade Aplicada ao' }).uncheck();
  await page.getByRole('checkbox', { name: 'Contabilidade de Custos (26)' }).check();
  await page.getByText('Exibindo 26 questões.').click();
  await page.getByRole('checkbox', { name: 'Contabilidade de Custos (26)' }).uncheck();
  await page.getByRole('checkbox', { name: 'Contabilidade Geral e NBCs (' }).check();
  await page.getByText('Exibindo 201 questões.').click();
  await page.getByRole('checkbox', { name: 'Contabilidade Geral e NBCs (' }).uncheck();
  await page.getByRole('checkbox', { name: 'Contabilidade Gerencial (28)' }).check();
  await page.getByText('Exibindo 28 questões.').click();
  await page.getByRole('checkbox', { name: 'Contabilidade Gerencial (28)' }).uncheck();
  await page.getByRole('checkbox', { name: 'Controladoria (10)' }).check();
  await page.getByText('Exibindo 10 questões.').click();
  await page.getByRole('checkbox', { name: 'Controladoria (10)' }).uncheck();
  await page.getByRole('checkbox', { name: 'Legislação e Ética' }).check();
  await page.getByText('Exibindo 32 questões.').click();
  await page.getByRole('checkbox', { name: 'Legislação e Ética' }).uncheck();
  await page.getByRole('checkbox', { name: 'Língua Portuguesa Aplicada (' }).check();
  await page.getByText('Exibindo 18 questões.').click();
  await page.getByRole('checkbox', { name: 'Língua Portuguesa Aplicada (' }).uncheck();
  await page.getByRole('checkbox', { name: 'Matemática Financeira e Estat' }).check();
  await page.getByText('Exibindo 17 questões.').click();
  await page.getByRole('checkbox', { name: 'Matemática Financeira e Estat' }).uncheck();
  await page.getByRole('checkbox', { name: 'Noções de Direito e Legislaçã' }).check();
  await page.getByText('Exibindo 23 questões.').click();
  await page.getByRole('checkbox', { name: 'Noções de Direito e Legislaçã' }).uncheck();
  await page.getByRole('checkbox', { name: 'Perícia Contábil (18)' }).check();
  await page.getByText('Exibindo 18 questões.').click();
  await page.getByRole('checkbox', { name: 'Perícia Contábil (18)' }).uncheck();
  await page.getByRole('checkbox', { name: 'Teoria da Contabilidade (30)' }).check();
  await page.getByText('Exibindo 30 questões.').click();
  await page.getByRole('checkbox', { name: 'Teoria da Contabilidade (30)' }).uncheck();
});