import { test, expect } from '@playwright/test';

test('Fluxo Estudante', async ({ page }) => {
  await page.goto('https://elrunix12.github.io/balanceterno/');
  await page.getByRole('checkbox', { name: 'Contabilidade Geral e NBCs (' }).check();
  await page.getByLabel('Ordenar por Ano:').selectOption('crescente');
  await page.getByLabel('Ordenar por Ano:').press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2025/2' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2025/1' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2024/2' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2024/1 RS' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2024/1', exact: true }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2023/2' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2023/1' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2022/2' }).press('Tab');
  await page.getByRole('checkbox', { name: 'CFC 2022/1' }).press('Tab');
  await page.getByRole('radio', { name: 'Sim (Padrão)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Mostrar apenas questões com' }).check();
  await page.getByRole('checkbox', { name: 'Mostrar apenas questões com' }).press('Shift+Tab');
  await page.getByRole('radio', { name: 'Sim (Padrão)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Mostrar apenas questões com' }).press('Shift+Tab');
  await page.getByRole('radio', { name: 'Sim (Padrão)' }).press('Shift+Tab');
  await page.getByRole('checkbox', { name: 'CFC 2022/1' }).press('Tab');
  await page.getByRole('radio', { name: 'Sim (Padrão)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Mostrar apenas questões com' }).press('Shift+Tab');
  await page.getByRole('radio', { name: 'Sim (Padrão)' }).press('ArrowRight');
  await page.getByRole('radio', { name: 'Não (Ocultar obsoletas)' }).check();
  await page.getByRole('radio', { name: 'Não (Ocultar obsoletas)' }).press('Tab');
  await page.getByRole('checkbox', { name: 'Mostrar apenas questões com' }).press('Tab');
  await page.getByRole('textbox', { name: 'Pesquisar por Palavra-Chave:' }).fill('peps');
  await page.getByRole('textbox', { name: 'Pesquisar por Palavra-Chave:' }).press('Enter');
  await page.getByRole('textbox', { name: 'Pesquisar por Palavra-Chave:' }).press('Tab');
  await page.locator('#btn-toggle-ementas').click();
  await page.locator('#search-ementas-input').fill('estoq');
  await page.locator('input[value="Estoques (NBC TG 16)"]').check();
  await page.getByText('(C) R$ 4.660,00.', { exact: true }).click();
  await page.getByRole('button', { name: 'Lançamentos Contábeis' }).click();
  await page.getByText('×', { exact: true }).click();
  await page.getByRole('button', { name: 'Limpar Todos os Filtros' }).click();
});